POST https://node-api-test-ften.onrender.com/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Primeiro video",
  "duration": 200
}


###


GET https://node-api-test-ften.onrender.com/videos


####


PUT https://node-api-test-ften.onrender.com/videos/bf39f328-f978-4b12-9207-d31e190c11ed
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Primeiro video",
  "duration": 180
}


####


DELETE https://node-api-test-ften.onrender.com/videos/bf39f328-f978-4b12-9207-d31e190c11ed